# aws cloudformation validate-template --template-body file://create-fargate-stack.yaml
# aws cloudformation create-stack --stack-name MyFargateApp --template-body file://create-fargate-stack.yaml --capabilities CAPABILITY_NAMED_IAM  --region ap-southeast-1

AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVpc

  MySubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVpc
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-southeast-1a

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HTTP traffic"
      VpcId: !Ref MyVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-app-repo

  MyEcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: MyEcsCluster

  MyEcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

Outputs:
  EcrRepositoryUri:
    Description: "URI of the ECR Repository"
    Value: !GetAtt
      - MyEcrRepository
      - RepositoryUri
  EcsClusterName:
    Description: "ECS Cluster Name"
    Value: !Ref MyEcsCluster
  SubnetId:
    Description: "Subnet ID"
    Value: !Ref MySubnet1
  SecurityGroupId:
    Description: "Security Group ID"
    Value: !Ref MySecurityGroup
  TaskExecutionRoleArn:
    Description: "Task Execution Role ARN"
    Value: !GetAtt
      - MyEcsTaskExecutionRole
      - Arn
